apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-server-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: iot-videonetics.com
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific          
          backend:
            service:
              name: backend-server-service
              port:
                number: 80
