apiVersion: v1
kind: Secret
metadata:
  name: backend-server-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ (.Files.Glob "secrets/videonetics.crt").AsSecrets | indent 2 }}
  tls.key: {{ (.Files.Glob "secrets/videonetics.key").AsSecrets | indent 2 }}
#   tls.crt: {{ .Files.Get "secrets/videonetics.crt" | b64enc }}
#   tls.key: {{ .Files.Get "secrets/videonetics.key" | b64enc }}
